/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import BackEnd.CI.Con_GRtoADP2;

import javax.swing.*;

import BackEnd.GLC.Regla2;
import BackEnd.GLC.Gramatica3;
import BackEnd.GLC.Gramatica2;
import BackEnd.ADP.Automata;
import BackEnd.ADP.Estado;
import BackEnd.GLC.TreeNodeDerivation;
import BackEnd.GLC.TreePanel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

import static vista.V_panelGLC.*;
import static vista.V_panelGLC.frame;

/**
 *
 * @author pedro
 */
public class V_panel extends javax.swing.JPanel {

    private boolean firstRule;
    private char cabecera;
    private char[] produccion;
    private ArrayList<Regla2> reglas;
    private ArrayList<Character> alfabeto;
    private DefaultTableModel tabla_default;
    private boolean prueba = false;

    /**
     * Creates new form V_panel
     */
    public V_panel() {
        initComponents();
        firstRule = false;
        reglas = new ArrayList();
        alfabeto = new ArrayList();

        tabla_default = new DefaultTableModel(new Object[]{"ejemplo", "ejemplo1"}, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Gill Sans BackEnd.MT", 1, 20)); // NOI18N
        jLabel1.setText("Gramatica libre de contexto");

        jLabel3.setFont(new java.awt.Font("Gill Sans BackEnd.MT", 1, 14)); // NOI18N
        jLabel3.setText("No Terminal");

        jLabel4.setFont(new java.awt.Font("Gill Sans BackEnd.MT", 1, 14)); // NOI18N
        jLabel4.setText("Producción");

        jTextField1.setText("S");
        jTextField1.setEnabled(false);
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });

        jTextField2.setText("aSb");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });

        jLabel5.setText("➜");

        jLabel6.setFont(new java.awt.Font("Gill Sans BackEnd.MT", 1, 14)); // NOI18N
        jLabel6.setText("Lista de reglas");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Gill Sans BackEnd.MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Eliminar");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 51, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Gill Sans BackEnd.MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Agregar");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        jLabel9.setFont(new java.awt.Font("Gill Sans BackEnd.MT", 1, 14)); // NOI18N
        jLabel9.setText("Cadena a evaluar");

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Gill Sans BackEnd.MT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Evaluar");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

        jLabel11.setFont(new java.awt.Font("Gill Sans BackEnd.MT", 1, 14)); // NOI18N
        jLabel11.setText("Estatus:");

        jLabel13.setFont(new java.awt.Font("Gill Sans BackEnd.MT", 1, 14)); // NOI18N

        jComboBox2.setFont(new java.awt.Font("Gill Sans BackEnd.MT", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Árbol de derivación", "Autómata de píla" }));

        jLabel12.setFont(new java.awt.Font("Gill Sans BackEnd.MT", 1, 14)); // NOI18N
        jLabel12.setText("Funciones:");

        jPanel5.setBackground(new java.awt.Color(0, 0, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Gill Sans BackEnd.MT", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Generar");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));

        jLabel15.setFont(new java.awt.Font("Gill Sans BackEnd.MT", 0, 12)); // NOI18N
        jLabel15.setText("• El nombre de la produccion (No-Terminal) debe ser");

        jLabel16.setText("una letra mayuscula del alfabeto (A-Z)");

        jLabel17.setText("• La regla puede ser una combinacion de Terminales y");

        jLabel18.setText("No-Terminales");

        jLabel19.setText("• La \"Lista de reglas\" hace referencia a el conjunto");

        jLabel20.setText("de producciones que componen la grámatica");

        jLabel21.setText("• El árbol de derivación se creara apartir de la cadena");

        jLabel22.setText("de evaluación");

        jLabel23.setFont(new java.awt.Font("Gill Sans BackEnd.MT", 1, 14)); // NOI18N
        jLabel23.setText("Ejemplos para utilizar:");

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L = 0^n 1^m 0^n  ;      n,m > 0", "L = a^i b c^k  ;      i,k > 0 & i < k", "L={Cadenas s/Σ {a,b} que sean: a^n b^n+1; P/n>=0}", "L = a^n b^n   ;     n > 0", "L = 0^2n 1^n  ;     n >=1" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Gill Sans BackEnd.MT", 1, 14)); // NOI18N
        jLabel24.setText("Detalles del funcionamiento de GLC:");

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/run.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(6, 6, 6))
                                            .addComponent(jTextField2)))
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel23)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(13, 13, 13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(jLabel12))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel17)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel16)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel24)
                                        .addComponent(jLabel15)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 360, 590));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 610, 590));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cadenas Aceptadas", "Cadenas No Aceptadas"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel9.setBackground(new java.awt.Color(0, 204, 0));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Gill Sans BackEnd.MT", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Analizar GLC ");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        if (!firstRule) {
            //jTextField1.setText("");
            jTextField2.setText("");
            firstRule = true;
        }
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        if (!firstRule) {
            //jTextField1.setText("");
            jTextField2.setText("");
            firstRule = true;
        }
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        //boton de agregar        
        try {
            cabecera = jTextField1.getText().charAt(0);
            if (Character.isUpperCase(cabecera)) {
                produccion = jTextField2.getText().toCharArray();
                if (produccion.length == 0) {
                    JOptionPane.showMessageDialog(this, "La regla de la producion no puede quedar en blanco\nsi desea utilizar epsilon ingrese el simbolo '?'", "Regla invalida", JOptionPane.ERROR_MESSAGE);
                } else {
                    reglas.add(new Regla2(cabecera, produccion));
                    String newItem = cabecera + " ➜ " + new String(produccion);
                    jComboBox1.addItem(newItem);
                    try {
                        jComboBox1.setSelectedIndex(jComboBox1.getSelectedIndex() + 1);
                    } catch (Exception ex) {
                    }
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField1.setEnabled(true);
                }
            } else {
                JOptionPane.showMessageDialog(this, "El nombre de la producion debe ser una sola letra en mayuscula", "Nombre de producción invalido", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se ingresaron valores correctos", "Datos invalido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        //boton de eliminar
        int index = jComboBox1.getSelectedIndex();
        jComboBox1.removeItemAt(index);
        reglas.remove(index);
        for (Regla2 r : reglas) {
            System.out.println(r);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        //boton para evaluar una cadena dada por el usuario
        Gramatica3 gr = new Gramatica3();

        for (Regla2 e : reglas) {
            gr.addProduccion(e.getNombre() + "", new String(e.getInstruccion()));
        }
        if (jTextField3.getText() == null || jTextField3.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Datos invalidos para rastrear la cadena", "Error en la cadena", JOptionPane.ERROR_MESSAGE);
        else {
            gr.recorrido1(jTextField3.getText());
            if (gr.F) {
                jLabel13.setText("Cadena valida");
            } else {
                jLabel13.setText("Cadena invalida");
            }
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        //boton para funciones
        if (jTextField3.getText() == null || jTextField3.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Datos invalidos para rastrear la cadena, Ingresa la cadena en el cuadro Cadena a evaluar valida", "Error en la cadena", JOptionPane.ERROR_MESSAGE);
        else if (jComboBox2.getSelectedIndex() == 0) {//Arbol de derivacion
            /**
             * A Q U I S E D E B E I N S E R T A R C O D I G O P A R A E L Á R B
             * O L D E D E R I V A C I Ó N
             */
            Gramatica2 gr = new Gramatica2();
            gr.setReglas(reglas);
            gr.recorrido1(jTextField3.getText());
            gr.construirArbol();
            TreeNodeDerivation raiz = gr.getRaiz();
            TreePanel tp = new TreePanel(raiz);
            mostrarGLC(raiz);
            frame.setVisible(true);

            javax.swing.JPanel jp = (javax.swing.JPanel) frame.getContentPane();
            jp.setSize(jPanel6.getSize());
            frame.setVisible(false);
            frame.dispose();
            jPanel6.setVisible(true);
            jPanel6.removeAll();
            jPanel6.add(jp);
            jPanel6.revalidate();
            jPanel6.repaint();
            revalidate();
            repaint();
        } else {//ADP
            Con_GRtoADP2 cv = new Con_GRtoADP2(reglas);
            V_panelConversionGLCAunADO panelADP = new V_panelConversionGLCAunADO(cv.estados);
            mostrarConversionGLCAunAUP(cv.estados);
            frameConversionGLCAunADP.setVisible(true);

            javax.swing.JPanel jp = (javax.swing.JPanel) frameConversionGLCAunADP.getContentPane();
            jp.setSize(jPanel6.getSize());
            frameConversionGLCAunADP.setVisible(false);
            frameConversionGLCAunADP.dispose();
            jPanel6.setVisible(true);
            jPanel6.removeAll();
            jPanel6.add(jp);
            jPanel6.revalidate();
            jPanel6.repaint();
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        reglas = new ArrayList();
        jComboBox1.removeAllItems();
        jTextField1.setText("");
        jTextField2.setText("");

        addOptionADP(jComboBox3.getSelectedIndex());
        addOptionGLC(jComboBox3.getSelectedIndex());
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        //jTable1.setModel(tabla_default);
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        alfabeto = new ArrayList();
        //if(!reglas.isEmpty()){
        //if (!prueba)
        test_GLC();
        //prueba = true;
        //}
    }//GEN-LAST:event_jLabel25MouseClicked

    private void addOptionADP(int i) {

        Automata a = new Automata();

        switch (i) {
            case 0:// L = 0^n 1^m 0^n ; n,m > 0
                a.addTransicion(0, '0', '?', '0', 1);
                a.addTransicion(1, '0', '?', '0', 1);
                a.addTransicion(1, '1', '?', '?', 2);
                a.addTransicion(2, '1', '?', '?', 2);
                a.addTransicion(2, '0', '0', '?', 3);
                a.addTransicion(3, '0', '0', '?', 3);
                a.addTransicion(3, '?', 'Z', '?', 4);
                a.setAceptacion(4, true);
                break;
            case 1:// L = a^i b c^k ; i,k > 0 & i < k
                a.addTransicion(0, 'a', '?', '1', 1);
                a.addTransicion(1, 'a', '?', '1', 1);
                a.addTransicion(1, 'b', '?', '?', 2);
                a.addTransicion(2, 'c', '1', '?', 3);
                a.addTransicion(3, 'c', '1', '?', 3);
                a.addTransicion(3, 'c', 'Z', '?', 4);
                a.addTransicion(4, '?', '?', '?', 4);
                a.setAceptacion(4, true);
                break;
            case 2://L={Cadenas s/Σ {a,b} que sean: a^n b^n+1; P/n>=0}
                a.addTransicion(0, 'a', '?', 'b', 0);
                a.addTransicion(0, '?', '?', '?', 1);
                a.addTransicion(1, 'b', 'b', '?', 1);
                a.addTransicion(1, 'b', '?', '?', 2);
                a.addTransicion(2, '?', 'Z', '?', 3);
                a.setAceptacion(3, true);
                break;
            case 3:// L = a^n b^n ; n > 0
                a.addTransicion(0, 'a', '?', '1', 0);
                a.addTransicion(0, 'b', '1', '?', 1);
                a.addTransicion(1, 'b', '1', '?', 1);
                a.addTransicion(1, '?', 'Z', '?', 2);
                a.setAceptacion(2, true);
                break;
            case 4: //L 0^2n 1^n  donde n >=1
                a.addTransicion(0, '0', '?', '?', 1);
                a.addTransicion(1, '0', '?', 'b', 2);
                a.addTransicion(2, '?', '?', '?', 0);
                a.addTransicion(2, '1', 'b', '?', 3);
                a.addTransicion(3, '1', 'b', '?', 3);
                a.addTransicion(3, '?', 'Z', '?', 4);
                a.setAceptacion(4, true);
                break;
        }
        ArrayList<Estado> es = new ArrayList();
        for (Estado e : a.getEstados()) {
            es.add(e);
        }
        V_panelConversionGLCAunADO panelADP = new V_panelConversionGLCAunADO(es);
        mostrarConversionGLCAunAUP(es);

        frameConversionGLCAunADP.setVisible(true);
        javax.swing.JPanel jp = (javax.swing.JPanel) frameConversionGLCAunADP.getContentPane();
        jp.setSize(jPanel6.getSize());
        frameConversionGLCAunADP.setVisible(false);
        frameConversionGLCAunADP.dispose();
        jPanel6.setVisible(true);
        jPanel6.removeAll();
        jPanel6.add(jp);
        jPanel6.revalidate();
        jPanel6.repaint();
        revalidate();
        repaint();
    }

    private void addOptionGLC(int i) {
        Regla2[] g;
        switch (i) {
            case 0://L = 0^n 1^m 0^n ; n,m >= 0
                g = new Regla2[4];
                g[0] = new Regla2('S', new char[]{'0', 'S', '0'});
                g[1] = new Regla2('S', new char[]{'0', 'A', '0'});
                g[2] = new Regla2('A', new char[]{'1', 'A'});
                g[3] = new Regla2('A', new char[]{'1'});
                break;
            case 1:// L = a^i b c^k ; i,k > 0 & i < k
                g = new Regla2[5];
                g[0] = new Regla2('S', new char[]{'a', 'A', 'c'});
                g[1] = new Regla2('A', new char[]{'a', 'A', 'B'});
                g[2] = new Regla2('A', new char[]{'b', 'c'});
                g[3] = new Regla2('B', new char[]{'c', 'B'});
                g[4] = new Regla2('B', new char[]{'c'});
                break;
            case 2://L={Cadenas s/Σ {a,b} que sean: a^n b^n+1; P/n>=0}
                g = new Regla2[2];
                g[0] = new Regla2('S', new char[]{'a', 'S', 'b'});
                g[1] = new Regla2('S', new char[]{'b'});
                break;
            case 3:
                g = new Regla2[2];
                g[0] = new Regla2('S', new char[]{'a', 'S', 'b'});
                g[1] = new Regla2('S', new char[]{'a', 'b'});
                break;
            case 4: //
                g = new Regla2[2];
                g[0] = new Regla2('S', new char[]{'0', '0', 'S', '1'});
                g[1] = new Regla2('S', new char[]{'0', '0', '1'});
                break;
            default:
                g = null;
        }
        for (Regla2 e : g) {
            reglas.add(e.getRegla());
            jComboBox1.addItem(e.getNombre() + " ➜ " + new String(e.getInstruccion()));
        }
    }

    private void test_GLC() {
        //consigue el afabeto
        Gramatica3 gr = new Gramatica3();
        for (Regla2 r : reglas) {
            String nombre = String.valueOf(r.getNombre());
            String regla = new String(r.getInstruccion());

            gr.addProduccion(nombre, regla);
        }

        for (Regla2 r : reglas) {
            for (char c : r.getInstruccion()) {
                if (!Character.isUpperCase(c) && !alfabeto.contains(c)) {
                    alfabeto.add(c);
                }
            }
        }

        //ejemplos del resultado de listas
        StringBuilder sb = new StringBuilder();
        for (Character c : alfabeto) {
            sb.append(c);
        }
        String Alfabeto = sb.toString();
        gr.lista(Alfabeto);
        String[] validos = gr.validos;
        String[] invalidos = gr.invalidos;
        /*
        for (int i = 0; i < 50; i++){
            validos[i]=generarCadenaAleatoria(4, alfabeto);
            invalidos[i]=generarCadenaAleatoria(4, alfabeto);
        }*/
        addCadenasTabla(validos, invalidos);
    }

    private String generarCadenaAleatoria(int longitud, ArrayList<Character> alf) {
        if (longitud <= 0 || alf.isEmpty()) {
            throw new IllegalArgumentException("Longitud no válida o lista de caracteres vacía");
        }

        java.util.Random random = new java.util.Random();
        StringBuilder sb = new StringBuilder();

        for (int i = 0; i < longitud; i++) {
            int indiceAleatorio = random.nextInt(alf.size());
            char caracterAleatorio = alf.get(indiceAleatorio);
            sb.append(caracterAleatorio);
        }

        return sb.toString();
    }

    private void addCadenasTabla(String[] validos, String[] invalidos) {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        System.out.println(validos.length + "- " + invalidos.length);
        for (int i = 0; i < 50; i++) {
            if (i < validos.length && i < invalidos.length) {
                modelo.addRow(new Object[]{validos[i], invalidos[i]});
            } else if (i < validos.length && i >= invalidos.length) {
                modelo.addRow(new Object[]{validos[i]});
            } else {
                modelo.addRow(new Object[]{"", invalidos[i]});
            }
        }
        jTable1.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
